# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/pschroeder/.cache/JetBrains/RemoteDev/dist/28f9dbfbcb7ad_CLion-2022.2/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/pschroeder/.cache/JetBrains/RemoteDev/dist/28f9dbfbcb7ad_CLion-2022.2/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pschroeder/repos/pam_telegram_authenticator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pschroeder/repos/pam_telegram_authenticator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/pschroeder/.cache/JetBrains/RemoteDev/dist/28f9dbfbcb7ad_CLion-2022.2/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/pschroeder/.cache/JetBrains/RemoteDev/dist/28f9dbfbcb7ad_CLion-2022.2/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pschroeder/repos/pam_telegram_authenticator/CMakeFiles /home/pschroeder/repos/pam_telegram_authenticator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pschroeder/repos/pam_telegram_authenticator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named pam_telegram_authenticator

# Build rule for target.
pam_telegram_authenticator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pam_telegram_authenticator
.PHONY : pam_telegram_authenticator

# fast build rule for target.
pam_telegram_authenticator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pam_telegram_authenticator.dir/build.make CMakeFiles/pam_telegram_authenticator.dir/build
.PHONY : pam_telegram_authenticator/fast

src/lib/PamWrapper/PamWrapper.o: src/lib/PamWrapper/PamWrapper.cpp.o
.PHONY : src/lib/PamWrapper/PamWrapper.o

# target to build an object file
src/lib/PamWrapper/PamWrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pam_telegram_authenticator.dir/build.make CMakeFiles/pam_telegram_authenticator.dir/src/lib/PamWrapper/PamWrapper.cpp.o
.PHONY : src/lib/PamWrapper/PamWrapper.cpp.o

src/lib/PamWrapper/PamWrapper.i: src/lib/PamWrapper/PamWrapper.cpp.i
.PHONY : src/lib/PamWrapper/PamWrapper.i

# target to preprocess a source file
src/lib/PamWrapper/PamWrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pam_telegram_authenticator.dir/build.make CMakeFiles/pam_telegram_authenticator.dir/src/lib/PamWrapper/PamWrapper.cpp.i
.PHONY : src/lib/PamWrapper/PamWrapper.cpp.i

src/lib/PamWrapper/PamWrapper.s: src/lib/PamWrapper/PamWrapper.cpp.s
.PHONY : src/lib/PamWrapper/PamWrapper.s

# target to generate assembly for a file
src/lib/PamWrapper/PamWrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pam_telegram_authenticator.dir/build.make CMakeFiles/pam_telegram_authenticator.dir/src/lib/PamWrapper/PamWrapper.cpp.s
.PHONY : src/lib/PamWrapper/PamWrapper.cpp.s

src/lib/TgAuthBot/TgAuthBot.o: src/lib/TgAuthBot/TgAuthBot.cpp.o
.PHONY : src/lib/TgAuthBot/TgAuthBot.o

# target to build an object file
src/lib/TgAuthBot/TgAuthBot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pam_telegram_authenticator.dir/build.make CMakeFiles/pam_telegram_authenticator.dir/src/lib/TgAuthBot/TgAuthBot.cpp.o
.PHONY : src/lib/TgAuthBot/TgAuthBot.cpp.o

src/lib/TgAuthBot/TgAuthBot.i: src/lib/TgAuthBot/TgAuthBot.cpp.i
.PHONY : src/lib/TgAuthBot/TgAuthBot.i

# target to preprocess a source file
src/lib/TgAuthBot/TgAuthBot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pam_telegram_authenticator.dir/build.make CMakeFiles/pam_telegram_authenticator.dir/src/lib/TgAuthBot/TgAuthBot.cpp.i
.PHONY : src/lib/TgAuthBot/TgAuthBot.cpp.i

src/lib/TgAuthBot/TgAuthBot.s: src/lib/TgAuthBot/TgAuthBot.cpp.s
.PHONY : src/lib/TgAuthBot/TgAuthBot.s

# target to generate assembly for a file
src/lib/TgAuthBot/TgAuthBot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pam_telegram_authenticator.dir/build.make CMakeFiles/pam_telegram_authenticator.dir/src/lib/TgAuthBot/TgAuthBot.cpp.s
.PHONY : src/lib/TgAuthBot/TgAuthBot.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pam_telegram_authenticator.o: src/pam_telegram_authenticator.cpp.o
.PHONY : src/pam_telegram_authenticator.o

# target to build an object file
src/pam_telegram_authenticator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pam_telegram_authenticator.dir/build.make CMakeFiles/pam_telegram_authenticator.dir/src/pam_telegram_authenticator.cpp.o
.PHONY : src/pam_telegram_authenticator.cpp.o

src/pam_telegram_authenticator.i: src/pam_telegram_authenticator.cpp.i
.PHONY : src/pam_telegram_authenticator.i

# target to preprocess a source file
src/pam_telegram_authenticator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pam_telegram_authenticator.dir/build.make CMakeFiles/pam_telegram_authenticator.dir/src/pam_telegram_authenticator.cpp.i
.PHONY : src/pam_telegram_authenticator.cpp.i

src/pam_telegram_authenticator.s: src/pam_telegram_authenticator.cpp.s
.PHONY : src/pam_telegram_authenticator.s

# target to generate assembly for a file
src/pam_telegram_authenticator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pam_telegram_authenticator.dir/build.make CMakeFiles/pam_telegram_authenticator.dir/src/pam_telegram_authenticator.cpp.s
.PHONY : src/pam_telegram_authenticator.cpp.s

src/test.o: src/test.cpp.o
.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i
.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s
.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... pam_telegram_authenticator"
	@echo "... test"
	@echo "... src/lib/PamWrapper/PamWrapper.o"
	@echo "... src/lib/PamWrapper/PamWrapper.i"
	@echo "... src/lib/PamWrapper/PamWrapper.s"
	@echo "... src/lib/TgAuthBot/TgAuthBot.o"
	@echo "... src/lib/TgAuthBot/TgAuthBot.i"
	@echo "... src/lib/TgAuthBot/TgAuthBot.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pam_telegram_authenticator.o"
	@echo "... src/pam_telegram_authenticator.i"
	@echo "... src/pam_telegram_authenticator.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

